
PROJECT_NAME 				= "MobvenProject"
PROJECT_BUNDLE 				= "com.mobven.MobvenProjectProd"
DEVELOPMENT_PROJECT_BUNDLE 	        = "com.mobven.MobvenProjectDev"
PROJECT_SCHEME 				= "MobvenProject"


#development build
lane :build_test do [values]
    #match(app_identifier: DEVELOPMENT_PROJECT_BUNDLE, type: "enterprise", readonly: true)
    build("DevelopmentRelease", 'enterprise', "#{DEVELOPMENT_PROJECT_BUNDLE}", "#{DEVELOPMENT_PROJECT_BUNDLE} pp")
end

# production build
lane :build_production do |values|
    #match(app_identifier: PROJECT_BUNDLE, type: "enterprise", readonly: true)
    build("ProductionRelease", 'enterprise', "#{PROJECT_BUNDLE}", "#{PROJECT_BUNDLE} pp")
end

def build(configuration, export_method, project_bundle, certificateName)
	gym( scheme: "#{PROJECT_SCHEME}",
	configuration: configuration,
	export_method: export_method,
	clean: true,
	export_options: {
		export_method: export_method,
		export_xcargs: "-allowProvisioningUpdates",
		provisioningProfiles: {
			project_bundle => certificateName
		}
	}
)   
end
